config/routes.rb
Smartvpn::Application.routes.draw do
  require 'sidekiq/web'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: 'users/passwords'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :billing do
    root to: "home#index"

    resources :payments, only: [:index, :new, :create] do
      member do
        get :merchant
      end
    end
    resources :promotions, only: [:create]
    resources :options, only: [:index, :create, :update, :destroy] do
      put :toggle, on: :member
    end
    resources :referrers, only: [:index]
    resources :servers, only: [:index] do
      get :download_config, on: :member
    end

    scope "/webmoney" do
      get "fail", to: "webmoney#fail", as: :webmoney_fail
      get "success", to: "webmoney#success", as: :webmoney_success
      match "result", to: "webmoney#result", as: :webmoney_result, via: [:get, :post]
    end

    scope "/robokassa" do
      get "fail", to: "robokassa#fail", as: :robokassa_fail
      get "success", to: "robokassa#success", as: :robokassa_success
      post "result", to: "robokassa#result", as: :robokassa_result
    end

    scope "/paypal" do
      get "fail", to: "paypal#fail", as: :paypal_fail
      get "success", to: "paypal#success", as: :paypal_success
      match "result", to: "paypal#result", as: :paypal_result, via: [:get, :post]
    end
  end

  namespace :admin do
    root to: "home#index"
    resources :servers do
      get :generate_config, on: :member
    end
    resources :plans
    resources :pay_systems, except: [:destroy]
    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get :payers
        get :this_month_payers
        get :emails_export
      end
      member do
        put :withdraw
        put :prolongate
        put :payment
        put :enable_test_period
        put :disable_test_period
        put :force_disconnect
      end
    end
    resources :connections, only: [:index, :show] do
      get :active, on: :collection
    end
    resources :traffic_reports, only: [:index] do
      collection do
        get :users
        get :date
        get :servers
      end
    end
    resources :transactions, only: [:index] do
      collection do
        get :payments
        get :withdrawals
      end
    end
    resources :promos, only: [:index, :new, :create, :edit, :update]
    resources :options, only: [:index, :new, :create, :edit, :update]
    resources :referrers, only: [:index]
  end

  namespace :api do
    match "/activate", to: "servers#activate", via: [:post]
    match "/auth", to: "authentication#auth", via: [:post]
    match "/disconnect", to: "connection#disconnect", via: [:post]
    match "/connect", to: "connection#connect", via: [:post]
  end

  match '/referrer', to: 'referrers#set_referrer', via: [:get]
  root to: 'main#index'

  authenticate :admin do
    mount Sidekiq::Web, at: '/sidekiq'
    mount PgHero::Engine, at: "pghero"
  end
end

app/models/promo.rb
class Promo < ActiveRecord::Base
  TYPES = %w( withdrawal )
  self.inheritance_column = 'sti_type'

  validates :name, :type, :promoter_type, presence: true

  scope :withdrawal, ->{ where(type: "withdrawal") }
  scope :active, ->{
    where("state='active' AND ? BETWEEN date_from AND date_to", Date.current) }

  state_machine :state, :initial => :pending do
    event :start do
      transition :pending => :active
    end

    event :stop do
      transition :active => :pending
    end
  end

  def promoter
    PromotersRepository.find_by_type(promoter_type)
  end
end

# == Schema Information
#
# Table name: promos
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  type          :string(255)
#  date_from     :date
#  date_to       :date
#  promoter_type :string(255)
#  promo_code    :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  attrs         :hstore           default({})
#  state         :string(255)
#

app/controllers/admin/promos_controller.rb
class Admin::PromosController < Admin::BaseController
  before_action :load_promo, only: [:new, :edit, :update, :create]

  def index
    @promos = Promo.all.page(params[:page]).decorate
  end

  def new
  end

  def create
    if @promo.update(resource_params)
      redirect_to edit_admin_promo_path(@promo), notice: "Акция успешно создана"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @promo.update(resource_params)
      redirect_to edit_admin_promo_path(@promo), notice: "Акция успешно обновлена"
    else
      render :edit
    end
  end

  private

  def load_promo
    @promo = Promo.find(params[:id]) if params[:id]
    @promo ||= Promo.new
  end

  def resource_params
    params[:promo].permit(:name, :promo_code, :promoter_type, :type,
                          :state, :date_from, :date_to, attrs: all_promoters_attributes)
  end

  def all_promoters_attributes
    PromotersRepository.all.inject([]) do |attrs, promoter|
      attrs + promoter.attributes
    end
  end
end

app/helpers/promos_helper.rb
module PromosHelper
  def promo_types
    select_options(Promo::TYPES.map { |type|
      [t("activerecord.attributes.promo.types.#{type}"), type]
    })
  end

  def promoter_types
    select_options(PromotersRepository.types.map { |type|
      [t("activerecord.attributes.promoter.types.#{type}"), type]
    })
  end

  def select_options(options)
    { as: :select, collection: options, include_blank: false }
  end
end

app/views/admin/promos/_form.html.slim
= simple_form_for [:admin, @promo], class: 'smart-form' do |f|
  = f.input :name
  = f.input :type, promo_types
  = f.input :promoter_type, promoter_types
  = f.input :date_from
  = f.input :date_to
  = f.input :promo_code
  = f.input :state, as: :select, collection: Promo.state_machine.states.map { |s| [t("activerecord.attributes.promo.states.#{s.name}"), s.name] }, include_blank: false

  = f.simple_fields_for :attrs do |a|
    - if @promo.promoter
      legend Аттрибуты
      br
      - @promo.promoter.attributes.each do |attribute_name|
        = a.input attribute_name, input_html: { value: @promo.attrs[attribute_name.to_s] }, label: t("activerecord.attributes.promoter.attributes.#{attribute_name}")

  br
  = f.submit "Применить", class: 'btn btn-primary btn-large'

app/views/admin/promos/edit.html.slim
= page_title('Акции', 'tags', 'Редактировать')
= render 'form'

app/views/admin/promos/index.html.slim
= page_title('Акции', 'tags')

.jarviswidget.jarviswidget-color-blue.jarviswidget-sortable
  = button_to "Добавить", new_admin_promo_path, method: :get, class: "btn btn-primary"
  br

  table.table.table-bordered
    thead
      tr
        th= "ID"
        th= "Название"
        th= "Тип"
        th= "Действие"
        th= "Статус"
        th= "Период действия"
        th

    tbody
      - @promos.each do |promo|
        tr
          td= promo.id
          td= promo.name
          td= promo.type
          td= promo.promoter_type
          td= promo.state
          td= promo.period
          td= link_to "Изменить", edit_admin_promo_path(promo)

app/views/admin/promos/new.html.slim
= page_title('Акции', 'tags', 'Новая')

= render 'form'