config/routes.rb
Smartvpn::Application.routes.draw do
  require 'sidekiq/web'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: 'users/passwords'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :billing do
    root to: "home#index"

    resources :payments, only: [:index, :new, :create] do
      member do
        get :merchant
      end
    end
    resources :promotions, only: [:create]
    resources :options, only: [:index, :create, :update, :destroy] do
      put :toggle, on: :member
    end
    resources :referrers, only: [:index]
    resources :servers, only: [:index] do
      get :download_config, on: :member
    end

    scope "/webmoney" do
      get "fail", to: "webmoney#fail", as: :webmoney_fail
      get "success", to: "webmoney#success", as: :webmoney_success
      match "result", to: "webmoney#result", as: :webmoney_result, via: [:get, :post]
    end

    scope "/robokassa" do
      get "fail", to: "robokassa#fail", as: :robokassa_fail
      get "success", to: "robokassa#success", as: :robokassa_success
      post "result", to: "robokassa#result", as: :robokassa_result
    end

    scope "/paypal" do
      get "fail", to: "paypal#fail", as: :paypal_fail
      get "success", to: "paypal#success", as: :paypal_success
      match "result", to: "paypal#result", as: :paypal_result, via: [:get, :post]
    end
  end

  namespace :admin do
    root to: "home#index"
    resources :servers do
      get :generate_config, on: :member
    end
    resources :plans
    resources :pay_systems, except: [:destroy]
    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get :payers
        get :this_month_payers
        get :emails_export
      end
      member do
        put :withdraw
        put :prolongate
        put :payment
        put :enable_test_period
        put :disable_test_period
        put :force_disconnect
      end
    end
    resources :connections, only: [:index, :show] do
      get :active, on: :collection
    end
    resources :traffic_reports, only: [:index] do
      collection do
        get :users
        get :date
        get :servers
      end
    end
    resources :transactions, only: [:index] do
      collection do
        get :payments
        get :withdrawals
      end
    end
    resources :promos, only: [:index, :new, :create, :edit, :update]
    resources :options, only: [:index, :new, :create, :edit, :update]
    resources :referrers, only: [:index]
  end

  namespace :api do
    match "/activate", to: "servers#activate", via: [:post]
    match "/auth", to: "authentication#auth", via: [:post]
    match "/disconnect", to: "connection#disconnect", via: [:post]
    match "/connect", to: "connection#connect", via: [:post]
  end

  match '/referrer', to: 'referrers#set_referrer', via: [:get]
  root to: 'main#index'

  authenticate :admin do
    mount Sidekiq::Web, at: '/sidekiq'
    mount PgHero::Engine, at: "pghero"
  end
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :user
  belongs_to :server

  delegate :hostname, to: :server

  def self.active
    ids = ActiveRecord::Base.connection.execute("
      SELECT id
      FROM connections AS c
      WHERE type='Connect'
        AND NOT EXISTS (
          SELECT 1
          FROM connections AS d
          WHERE
            type='Disconnect'
            AND c.user_id=d.user_id
            AND c.created_at < d.created_at
        );
    ").values.flatten
    where(id: ids)
  end
end

# == Schema Information
#
# Table name: connections
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  server_id   :integer
#  traffic_in  :float
#  traffic_out :float
#  type        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/connections/connect.rb
class Connect < Connection
end

# == Schema Information
#
# Table name: connections
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  server_id   :integer
#  traffic_in  :float
#  traffic_out :float
#  type        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/connections/disconnect.rb
class Disconnect < Connection
  include LastDaysFilterable

  validates :traffic_in, :traffic_out, presence: true
end

# == Schema Information
#
# Table name: connections
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  server_id   :integer
#  traffic_in  :float
#  traffic_out :float
#  type        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/admin/connections_controller.rb
class Admin::ConnectionsController < Admin::BaseController
  def index
    @connections = connections.order("id DESC").page params[:page]
  end

  def active
    @connections = connections.active.order("id DESC").page params[:page]
  end

  def show
    @connection = Connection.find(params[:id])
  end

  private

  def connections
    search.result
  end

  def search
    Connection.search(params[:q])
  end
  helper_method :search
end

app/controllers/api/connection_controller.rb
class Api::ConnectionController < Api::BaseController
  before_action :valid_api_call?

  def connect
    connect_object = connector.invoke
    # TODO:
    # am:serializers temporary don't work with rails 4.2
    # render status: 200, json: connect_object, serializer: Api::ConnectSerializer
    render status: 200, json: Api::ConnectSerializer.new(connect_object).to_json
  end

  def disconnect
    disconnect_object = connector.invoke
    # render status: 200, json: disconnect_object, serializer: Api::DisconnectSerializer
    render status: 200, json: Api::DisconnectSerializer.new(disconnect_object).to_json
  end

  private

  def connector
    Connector.new(action_params)
  end

  def action_params
    {
      login: params[:login],
      hostname: params[:hostname],
      traffic_in: params[:traffic_in],
      traffic_out: params[:traffic_out],
      action: params[:action]
    }
  end
end

app/views/admin/connections/active.html.slim
h3 Активные подключения

.search
  = search_form_for [:admin, search], url: active_admin_connections_path do |f|
    p
      = f.label :user
      = f.select :user_id_eq, options_for_select(User.all.map { |u| [u.email, u.id] }), include_blank: true
    p
      = f.label :server
      = f.select :server_id_eq, options_for_select(Server.all.map { |s| [s.hostname, s.id] }), include_blank: true
    p
      = f.submit

.info
  table.table.table-bordered
    thead
      tr
        th= "ID"
        th= "Пользователь"
        th= "Сервер"
        th= "Дата"
        -# TODO:
        /здесь сделать колонки с траффиком по подключению

    - @connections.each do |connection|
      tr
        td= connection.id
        td= link_to connection.user.email, admin_user_path(connection.user)
        td= link_to connection.hostname, admin_server_path(connection.server)
        td= human_date(connection.created_at)

= paginate @connections

app/views/admin/connections/index.html.slim
.search
  = search_form_for [:admin, search] do |f|
    p
      = f.label :user
      = f.select :user_id_eq, options_for_select(User.all.map { |u| [u.email, u.id] }), include_blank: true
    p
      = f.label :server
      = f.select :server_id_eq, options_for_select(Server.all.map { |s| [s.hostname, s.id] }), include_blank: true
    p
      = f.submit
    = link_to "Активные", active_admin_connections_path

.info
  table.table.table-bordered
    thead
      tr
        th= "ID"
        th= "Пользователь"
        th= "Сервер"
        th= "Событие"
        th= "Траффик"
        th= "Дата"

    - @connections.each do |connection|
      tr
        td= connection.id
        td= link_to connection.user.email, admin_user_path(connection.user)
        td= link_to connection.hostname, admin_server_path(connection.server)
        td= human_connection(connection.type)
        td= human_traffic(connection.traffic_in + connection.traffic_out) if connection.is_a? Disconnect
        td= human_date(connection.created_at)

= paginate @connections

app/views/admin/connections/show.html.slim
| Тут отобразить текущий траффик по коннекту и график по траффику, можно статический