config/routes.rb
Smartvpn::Application.routes.draw do
  require 'sidekiq/web'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: 'users/passwords'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :billing do
    root to: "home#index"

    resources :payments, only: [:index, :new, :create] do
      member do
        get :merchant
      end
    end
    resources :promotions, only: [:create]
    resources :options, only: [:index, :create, :update, :destroy] do
      put :toggle, on: :member
    end
    resources :referrers, only: [:index]
    resources :servers, only: [:index] do
      get :download_config, on: :member
    end

    scope "/webmoney" do
      get "fail", to: "webmoney#fail", as: :webmoney_fail
      get "success", to: "webmoney#success", as: :webmoney_success
      match "result", to: "webmoney#result", as: :webmoney_result, via: [:get, :post]
    end

    scope "/robokassa" do
      get "fail", to: "robokassa#fail", as: :robokassa_fail
      get "success", to: "robokassa#success", as: :robokassa_success
      post "result", to: "robokassa#result", as: :robokassa_result
    end

    scope "/paypal" do
      get "fail", to: "paypal#fail", as: :paypal_fail
      get "success", to: "paypal#success", as: :paypal_success
      match "result", to: "paypal#result", as: :paypal_result, via: [:get, :post]
    end
  end

  namespace :admin do
    root to: "home#index"
    resources :servers do
      get :generate_config, on: :member
    end
    resources :plans
    resources :pay_systems, except: [:destroy]
    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get :payers
        get :this_month_payers
        get :emails_export
      end
      member do
        put :withdraw
        put :prolongate
        put :payment
        put :enable_test_period
        put :disable_test_period
        put :force_disconnect
      end
    end
    resources :connections, only: [:index, :show] do
      get :active, on: :collection
    end
    resources :traffic_reports, only: [:index] do
      collection do
        get :users
        get :date
        get :servers
      end
    end
    resources :transactions, only: [:index] do
      collection do
        get :payments
        get :withdrawals
      end
    end
    resources :promos, only: [:index, :new, :create, :edit, :update]
    resources :options, only: [:index, :new, :create, :edit, :update]
    resources :referrers, only: [:index]
  end

  namespace :api do
    match "/activate", to: "servers#activate", via: [:post]
    match "/auth", to: "authentication#auth", via: [:post]
    match "/disconnect", to: "connection#disconnect", via: [:post]
    match "/connect", to: "connection#connect", via: [:post]
  end

  match '/referrer', to: 'referrers#set_referrer', via: [:get]
  root to: 'main#index'

  authenticate :admin do
    mount Sidekiq::Web, at: '/sidekiq'
    mount PgHero::Engine, at: "pghero"
  end
end

app/models/traffic_report.rb
class TrafficReport
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :result, :date_from, :date_to

  def initialize(attributes={})
    attributes.each do |name, value|
      send("#{name}=", value)
    end unless attributes.nil?
  end

  def result
    @result = build_report.where("created_at >= ? AND created_at <= ?", date_from, date_to)
  end

  def date_from
    @date_from || Date.current.beginning_of_month
  end

  def date_to
    @date_to || Date.current.end_of_month
  end

  # To behave as active model
  def persisted?
    false
  end

end

app/models/traffic_reports/date_traffic_report.rb
class DateTrafficReport < TrafficReport

  private

  def build_report
    # TODO:
    # Группируется только по дате,
    # получается что в одну ячейку сгруппируются допустим все подключения за 15 сентбяря
    # а также и за 15 октября, ноября и тп.
    # группировать по уникальной дате.
    Disconnect.group("DATE_TRUNC('day', created_at)").
                select("
                  DATE_TRUNC('day', created_at) AS date,
                  SUM(traffic_in) AS traffic_in,
                  SUM(traffic_out) AS traffic_out").
                order("date DESC")
  end


end

app/models/traffic_reports/server_traffic_report.rb
class ServerTrafficReport < TrafficReport

  private

  def build_report
    Disconnect.group("server_id").
                select("
                  server_id,
                  SUM(traffic_in) AS traffic_in,
                  SUM(traffic_out) AS traffic_out
               ").
                order("server_id ASC")
  end
end

app/models/traffic_reports/user_traffic_report.rb
class UserTrafficReport < TrafficReport

  private

  def build_report
    Disconnect.group("user_id").
                select("
                  user_id,
                  SUM(traffic_in) AS traffic_in,
                  SUM(traffic_out) AS traffic_out
               ").
                 order("user_id ASC")
  end
end

app/controllers/admin/traffic_reports_controller.rb
class Admin::TrafficReportsController < Admin::BaseController
  def index
  end

  def users
  end

  def date
  end

  def servers
  end

  private

  def traffic_reports
    report.result
  end
  helper_method :traffic_reports

  def report
    "#{action_name.singularize.capitalize}TrafficReport".constantize.new(params[:traffic_report])
  end
  helper_method :report
end

app/views/admin/traffic_reports/_filter.html.slim
h2 Фильтр

= simple_form_for TrafficReport.new(params[:traffic_report]), url: request.fullpath, method: :get do |f|
  = f.input :date_from, as: :datepicker
  = f.input :date_to, as: :datepicker
  = f.submit :submit

app/views/admin/traffic_reports/_submenu.html.slim
ul
  li= link_to "Отчеты по траффику", admin_traffic_reports_path
  li= link_to "По пользователям", users_admin_traffic_reports_path
  li= link_to "По дате", date_admin_traffic_reports_path
  li= link_to "По серверам", servers_admin_traffic_reports_path

app/views/admin/traffic_reports/date.html.slim
h2 Траффик по дате
= render partial: "submenu"
= render partial: "filter"

.info
  table.table.table-bordered
    tr
      th Дата
      th Входящий траффик
      th Исходящий траффик
      th Итого

    - traffic_reports.each do |report|
      tr
        td= human_date(report.date)
        td= human_traffic report.traffic_in
        td= human_traffic report.traffic_out
        td= human_traffic report.traffic_in + report.traffic_out

app/views/admin/traffic_reports/index.html.slim
h2 Отчеты по траффику
= render partial: "submenu"

app/views/admin/traffic_reports/servers.html.slim
h2 Траффик по серверам
= render partial: "submenu"
= render partial: "filter"

.info
  table.table.table-bordered
    tr
      th Сервер
      th Входящий траффик
      th Исходящий траффик
      th Итого

    - traffic_reports.each do |report|
      tr
        td= report.server.hostname
        td= human_traffic report.traffic_in
        td= human_traffic report.traffic_out
        td= human_traffic report.traffic_in + report.traffic_out

app/views/admin/traffic_reports/users.html.slim
h2 Траффик по пользователям
= render partial: "submenu"
= render partial: "filter"

.info
  table.table.table-bordered
    tr
      th Пользователь
      th Входящий траффик
      th Исходящий траффик
      th Итого

    - traffic_reports.each do |report|
      tr
        td= report.user.email
        td= human_traffic report.traffic_in
        td= human_traffic report.traffic_out
        td= human_traffic report.traffic_in + report.traffic_out