config/routes.rb
Smartvpn::Application.routes.draw do
  require 'sidekiq/web'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: 'users/passwords'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :billing do
    root to: "home#index"

    resources :payments, only: [:index, :new, :create] do
      member do
        get :merchant
      end
    end
    resources :promotions, only: [:create]
    resources :options, only: [:index, :create, :update, :destroy] do
      put :toggle, on: :member
    end
    resources :referrers, only: [:index]
    resources :servers, only: [:index] do
      get :download_config, on: :member
    end

    scope "/webmoney" do
      get "fail", to: "webmoney#fail", as: :webmoney_fail
      get "success", to: "webmoney#success", as: :webmoney_success
      match "result", to: "webmoney#result", as: :webmoney_result, via: [:get, :post]
    end

    scope "/robokassa" do
      get "fail", to: "robokassa#fail", as: :robokassa_fail
      get "success", to: "robokassa#success", as: :robokassa_success
      post "result", to: "robokassa#result", as: :robokassa_result
    end

    scope "/paypal" do
      get "fail", to: "paypal#fail", as: :paypal_fail
      get "success", to: "paypal#success", as: :paypal_success
      match "result", to: "paypal#result", as: :paypal_result, via: [:get, :post]
    end
  end

  namespace :admin do
    root to: "home#index"
    resources :servers do
      get :generate_config, on: :member
    end
    resources :plans
    resources :pay_systems, except: [:destroy]
    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get :payers
        get :this_month_payers
        get :emails_export
      end
      member do
        put :withdraw
        put :prolongate
        put :payment
        put :enable_test_period
        put :disable_test_period
        put :force_disconnect
      end
    end
    resources :connections, only: [:index, :show] do
      get :active, on: :collection
    end
    resources :traffic_reports, only: [:index] do
      collection do
        get :users
        get :date
        get :servers
      end
    end
    resources :transactions, only: [:index] do
      collection do
        get :payments
        get :withdrawals
      end
    end
    resources :promos, only: [:index, :new, :create, :edit, :update]
    resources :options, only: [:index, :new, :create, :edit, :update]
    resources :referrers, only: [:index]
  end

  namespace :api do
    match "/activate", to: "servers#activate", via: [:post]
    match "/auth", to: "authentication#auth", via: [:post]
    match "/disconnect", to: "connection#disconnect", via: [:post]
    match "/connect", to: "connection#connect", via: [:post]
  end

  match '/referrer', to: 'referrers#set_referrer', via: [:get]
  root to: 'main#index'

  authenticate :admin do
    mount Sidekiq::Web, at: '/sidekiq'
    mount PgHero::Engine, at: "pghero"
  end
end

app/models/pay_system.rb
class PaySystem < ActiveRecord::Base
  CURRENCIES = %w(usd rub eur)

  has_many :payments
  validates :name, :code, presence: true
  scope :enabled, ->{ where(state: :enabled) }

  state_machine :state, :initial => :disabled do
    event :enable do
      transition :disabled => :enabled
    end

    event :disable do
      transition :enabled => :disabled
    end
  end

end

# == Schema Information
#
# Table name: pay_systems
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  code        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  description :text
#  state       :string(255)
#  currency    :string(255)      default("usd")
#

app/controllers/admin/pay_systems_controller.rb
class Admin::PaySystemsController < Admin::BaseController
  before_action :load_resource, only: [:show, :edit, :update, :destroy]

  def index
    @pay_systems = PaySystem.all.decorate
  end

  def show
  end

  def new
    @pay_system = PaySystem.new
  end

  def create
    @pay_system = PaySystem.new(resource_params)
    if @pay_system.save
      redirect_to admin_pay_systems_path, notice: "Платежная система успешно добавлена"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pay_system.update(resource_params)
      redirect_to admin_pay_systems_path, notice: "Платежная система успешно обновлена"
    else
      render :edit
    end
  end

  private

  def load_resource
    @pay_system = PaySystem.find(params[:id])
  end

  def resource_params
    params.require(:pay_system).permit(:name, :code, :description, :state, :currency)
  end
end

app/views/admin/pay_systems/_form.html.slim
= simple_form_for [:admin, @pay_system] do |f|
  = f.input :name
  = f.input :code
  = f.input :description
  = f.input :state,
    as: :select,
    collection: PaySystem.state_machine.states.map { |s| [t("admin.pay_systems.states.#{s.name}"), s.name] },
    include_blank: false
  = f.input :currency, as: :select, collection: PaySystem::CURRENCIES.map { |c| [c, c] }
  br
  = f.submit "Применить", class: 'btn btn-primary btn-large'

app/views/admin/pay_systems/edit.html.slim
= page_title('Платежные системы', 'money', 'Редактировать')
= render partial: "form"

app/views/admin/pay_systems/index.html.slim
= page_title('Платежные системы', 'money')

.jarviswidget.jarviswidget-color-blue.jarviswidget-sortable
  = button_to "Добавить", new_admin_pay_system_path, method: :get, class: "btn btn-primary"
  br

  table.table.table-bordered
    thead
      tr
        th= "#"
        th= "Название"
        th= "Код"
        th= "Статус"
        th

    tbody
      - @pay_systems.each do |pay_system|
        tr
          td= pay_system.id
          td= pay_system.title
          td= pay_system.code
          td class="state #{pay_system.state}"
            = pay_system.human_state
          th
            = link_to "Изменить", edit_admin_pay_system_path(pay_system)

app/views/admin/pay_systems/new.html.slim
h1= "Добавить новый сервер"
= render partial: "form"

app/views/admin/pay_systems/show.html.slim
= page_title('Платежная система', 'money', @pay_system.name)

= link_to "Редактировать", edit_admin_pay_system_path(@pay_system), method: :get
br

= show_for @pay_system do |pay_system|
  = pay_system.attribute :id
  = pay_system.attribute :name
  = pay_system.attribute :code
  = pay_system.attribute :description
  = pay_system.attribute :state